/*
 * @Author: ningyongheng ningyongheng@jeejio.com
 * @Date: 2025-01-09 16:23:19
 * @LastEditors: ningyongheng ningyongheng@jeejio.com
 * @LastEditTime: 2025-01-10 16:07:29
 * @FilePath: /my-website/sidebars.ts
 * @Description: 这是默认设置,请设置`customMade`, 打开koroFileHeader查看配置 进行设置: https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%A
 */
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  someSidebar: [
    "intro",
    "tutorial-basics/congratulations",
    "tutorial-basics/create-a-blog-post",
    "tutorial-basics/create-a-page",
    "tutorial-basics/deploy-your-site",
    "tutorial-basics/markdown-features",
    "tutorial-extras/manage-docs-versions",
    "tutorial-extras/translate-your-site",
    {
      type: "category",
      label: "Tutorial",
      items: ["tutorial-basics/create-a-document"],
    },
  ],
};

export default sidebars;
